#
## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

# override common configurations in common module
servicecomb-config-order: 10

servicecomb:
  service:
    application: demo-java-chassis-cse-v1
    name: consumer
    version: 0.0.1
  registry:
    sc:
      address: https://cse.cn-south-1.myhuaweicloud.com
      watch: false
  config:
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com
      fileSource: consumer.yaml

  rest:
    address: 0.0.0.0:9092  # should be same with server.port to use web container

  routeRule:
    provider: |
      - precedence: 1
        match:
          headers:
            canary:
              exact: new
        route:
          - weight: 20
            tags:
              version: 0.0.1
          - weight: 80
            tags:
              version: 0.0.2
      - precedence: 2
        match:
          headers:
            canary:
              exact: old
        route:
          - weight: 100
            tags:
              version: 0.0.1
      - precedence: 3
        match:
          headers:
            canary:
              exact: fallback
        route:
          - weight: 100
            tags:
              version: 0.0.3
        fallback:
          - weight: 20
            tags:
              version: 0.0.1
          - weight: 80
            tags:
              version: 0.0.2
      - precedence: 4
        emptyProtection: false
        match:
          headers:
            canary:
              exact: emptyProtectionClose100
        route:
          - weight: 100
            tags:
              version: 0.0.3
      - precedence: 5
        emptyProtection: false
        match:
          headers:
            canary:
              exact: emptyProtectionCloseLess100
        route:
          - weight: 50
            tags:
              version: 0.0.3
      - precedence: 6
        emptyProtection: false
        match:
          headers:
            canary:
              exact: emptyProtectionCloseFallback
        route:
          - weight: 100
            tags:
              version: 0.0.3
        fallback:
          - weight: 100
            tags:
              version: 0.0.1
      - precedence: 7
        emptyProtection: false
        match:
          headers:
            canary:
              exact: emptyProtectionClose100-2
        route:
          - weight: 50
            tags:
              version: 0.0.1
          - weight: 50
            tags:
              version: 0.0.3


  router:
    type: router
    header: canary

  # Configure AK/SK credentials if needed. Default not enabled.
  credentials:
    akskEnabled: true
    accessKey: ${CREDENTIALS_AK}
    secretKey: ${CREDENTIALS_SK}
    akskCustomCipher: default
    project: cn-south-1

